# Example of Nextcloud deployment. The operator will receive this specification and will create a deployment of two "echo" pods.
apiVersion: Nextcloud/v1
kind: Nextcloud # Identifier of the resource type.
metadata:
  name: test-nextcloud-imcsk9 # Name of the "Echo" custom resource instance, may be changed to your liking
  namespace: nextcloud-operator # Namespace must exist and account in KUBECONFIG must have sufficient permissions
spec:
  replicas: 1 # Number of "nextcloud" pods created.
