use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Struct corresponding to the Specification (`spec`) part of the `Echo` resource, directly
/// reflects context of the `nextcloud.yaml` file to be found in this repository.
/// The `Echo` struct will be generated by the `CustomResource` derive macro.
#[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[kube(
    group = "nextcloud",
    version = "v1",
    kind = "Nextcloud",
    plural = "Nextclouds",
    derive = "PartialEq",
    namespaced
)]
pub struct NextcloudSpec {
    pub replicas: i32,
    pub php_image: String,
}
