use kube::{CustomResource, CustomResourceExt, client::Client, Api, api::PatchParams, api::Patch};
use k8s_openapi::apiextensions_apiserver::pkg::apis::apiextensions::v1::CustomResourceDefinition;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use log::{info, debug};
//use kube::{client::Client, runtime::controller::Action, runtime::Controller, Api};

pub const RESOURCE_NAME: &str = "nextclouds.sotolitolabs.com";

/// Struct corresponding to the Specification (`spec`) part of the `Echo` resource, directly
/// reflects context of the `nextcloud.yaml` file to be found in this repository.
/// The `Echo` struct will be generated by the `CustomResource` derive macro.
#[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[kube(
    group = "sotolitolabs.com",
    version = "v1",
    kind = "Nextcloud",
    plural = "nextclouds",
    derive = "PartialEq",
    namespaced
)]
#[kube(status = "NextcloudStatus")]
pub struct NextcloudSpec {
    pub replicas: i32,
    pub php_image: String,
    pub nginx_image: String,
    pub image_pull_secret: String,
    pub version: String,
    pub maintenance: bool,
}

#[derive(Deserialize, Serialize, Clone, Debug, Default, PartialEq, JsonSchema)]
pub struct NextcloudStatus {
    pub installed: bool,
    pub configured: i32,
    pub maintenance: bool,
    pub last_backup: String,
    pub state_hash: String,
}

/// Creates the Nextcloud CRD
/// This helps to avoid the manual creation of the Nextcloud CRD
/// TODO: return proper values
pub async fn create_crd(client: Client) {
    //let nextclouds = Api::default_namespaced(client.clone());
    let crds: Api<CustomResourceDefinition> = Api::all(client.clone());
    info!("Creating Nextcloud CRD");
    match crds.patch(RESOURCE_NAME,
        &PatchParams::apply("imcsk8-test"),
        &Patch::Apply(Nextcloud::crd())
    ).await {
        //Ok(r) => info!("{} CRD created {:?}", RESOURCE_NAME, r),
        Ok(r) => info!("{} CRD created", RESOURCE_NAME),
        Err(e) => info!("Error creating {} CRD {:?}!", RESOURCE_NAME, e),
    };
}
